[package]
name = "zynq-memflow"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/slack2450/zynq-memflow.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memflow = "0.1.5"
memflow-win32 = "0.1.5"
simplelog = "0.12.0"
